
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Vasily Frolov
tagline: Системный администратор
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: thorin39@gmail.com
#phone: 012 345 6789
website: thorin39.github.io #do not add http://
linkedin: thorin39
github: thorin39
twitter: '@thorin39'


# Tracker
analytics: UA-97192713-1
#Update all the sections by editing the files inside _includes folder.
